from pathlib import Path

p = Path('receive/main.js')
s = p.read_text()
old = '''  const selected = ranked.slice(0, budget);\n  const excluded = ranked.slice(budget);\n  decodePortfolio.exploreSlot = void 0;\n  const sequence = Number(sourceSequence);\n  if (selected.length && excluded.length && Number.isFinite(sequence) && Math.trunc(sequence) % PORTFOLIO_EXPLORE_EVERY === 0) {\n    const exploreIndex = Math.floor(Math.trunc(sequence) / PORTFOLIO_EXPLORE_EVERY) % excluded.length;\n    const explore = excluded[exploreIndex];\n    selected[selected.length - 1] = explore;\n    decodePortfolio.exploreSlot = explore.gridSlot;\n  }\n'''
new = '''  const selected = ranked.slice(0, budget);\n  const excluded = ranked.slice(budget);\n  decodePortfolio.exploreSlot = void 0;\n  const sequence = Number(sourceSequence);\n  // v168 weak slots already arrive here only on their sparse recovery-probe\n  // frame. Do not let best-K immediately rank that probe back out: force one\n  // due weak slot into the portfolio for this frame. If multiple weak slots\n  // share a probe phase, rotate them rather than paying for all at once.\n  const dueWeak = excluded.filter((region) => {\n    const slot = Number(region.gridSlot);\n    return Number.isInteger(slot) && slot >= 0 && slot < SLOT_METRIC_COUNT && slotAdaptiveWeak[slot];\n  });\n  if (selected.length && dueWeak.length && Number.isFinite(sequence)) {\n    const probeIndex = Math.floor(Math.trunc(sequence) / SLOT_WEAK_PROBE_EVERY) % dueWeak.length;\n    const probe = dueWeak[probeIndex];\n    selected[selected.length - 1] = probe;\n    decodePortfolio.exploreSlot = probe.gridSlot;\n  } else if (selected.length && excluded.length && Number.isFinite(sequence) && Math.trunc(sequence) % PORTFOLIO_EXPLORE_EVERY === 0) {\n    const exploreIndex = Math.floor(Math.trunc(sequence) / PORTFOLIO_EXPLORE_EVERY) % excluded.length;\n    const explore = excluded[exploreIndex];\n    selected[selected.length - 1] = explore;\n    decodePortfolio.exploreSlot = explore.gridSlot;\n  }\n'''
if old not in s:
    raise SystemExit('portfolio exploration anchor missing')
p.write_text(s.replace(old, new, 1))
