PER_BATCH;\n            salvageAllowed[i] = uint8_t(allowExpensiveRepair);\n            bool repairSpentThisTrack = false;\n            auto* cache = guidedTurboTrack(track.id);''',
    expected=1
)
replace(
    "vendor/decimen-codec/source/wrapper/decimen_codec.cpp",
    '''                        auto retryLocalResidual = [&]() {\n                            if (stableModuleSize > GUIDED_TURBO_CANARY_MIN_MODULE)\n                                return false;''',
    '''                        auto retryLocalResidual = [&]() {\n                            if (!allowExpensiveRepair || stableModuleSize > GUIDED_TURBO_CANARY_MIN_MODULE)\n                                return false;'''
)
replace(
    "vendor/decimen-codec/source/wrapper/decimen_codec.cpp",
    '''                            bool localRsUsed = false;\n                            auto localDecoded = decodeTurboStableRS(*cache, track, frameTransform,\n                                                                    yPlane, width, height, stride,\n                                                                    refined->x, refined->y, localLevels, *metrics,\n                                                                    centerOnlyRs, progressiveRs, &localRsUsed);\n                            if (localRsUsed)\n                                ++metrics->sparseRsFallbacks;\n                            return commitTurbo(i, localDecoded, refined->x, refined->y);''',
    '''                            bool localRsUsed = false;\n                            bool localRepairAttempted = false;\n                            bool localRepairSuccess = false;\n                            auto localDecoded = decodeTurboStableRS(*cache, track, frameTransform,\n                                                                    yPlane, width, height, stride,\n                                                                    refined->x, refined->y, localLevels, *metrics,\n                                                                    centerOnlyRs, progressiveRs, allowExpensiveRepair,\n                                                                    &localRsUsed, &localRepairAttempted, &localRepairSuccess);\n                            if (localRsUsed)\n                                ++metrics->sparseRsFallbacks;\n                            if (localRepairAttempted && trackBit) {\n                                metrics->erasureRepairAttemptMask |= trackBit;\n                                if (!repairSpentThisTrack) { repairSpentThisTrack = true; ++repairTracksSpent; }\n                            }\n                            if (localRepairSuccess && trackBit) metrics->erasureRepairSuccessMask |= trackBit;\n                            return commitTurbo(i, localDecoded, refined->x,