) {\n                                    if (allowExpensiveRepair) {\n                                        metrics->erasureRepairAttemptMask |= trackBit;\n                                        if (!repairSpentThisTrack) { repairSpentThisTrack = true; ++repairTracksSpent; }\n                                    } else {\n                                        metrics->erasureRepairSuppressedMask |= trackBit;\n                                    }\n                                }\n                                if (repairSuccess && trackBit) metrics->erasureRepairSuccessMask |= trackBit;'''
)
replace(
    "vendor/decimen-codec/source/wrapper/decimen_codec.cpp",
    '''                                const bool robustRetryWorthwhile = centerOnlyRs &&\n                                    stableModuleSize >= GUIDED_TURBO_CANARY_MIN_MODULE;''',
    '''                                const bool robustRetryWorthwhile = allowExpensiveRepair && !repairSpentThisTrack && centerOnlyRs &&\n                                    stableModuleSize >= GUIDED_TURBO_CANARY_MIN_MODULE;'''
)
replace(
    "vendor/decimen-codec/source/wrapper/decimen_codec.cpp",
    '''                                    bool robustRsUsed = false;\n                                    decoded = decodeTurboStableRS(*cache, track, frameTransform,\n                                                                  yPlane, width, height, stride,\n                                                                  dx, dy, levels, *metrics,\n                                                                  false, true, &robustRsUsed);\n                                    if (robustRsUsed)\n                                        ++metrics->sparseRsFallbacks;''',
    '''                                    bool robustRsUsed = false;\n                                    bool robustRepairAttempted = false;\n                                    bool robustRepairSuccess = false;\n                                    decoded = decodeTurboStableRS(*cache, track, frameTransform,\n                                                                  yPlane, width, height, stride,\n                                                                  dx, dy, levels, *metrics,\n                                                                  false, true, true, &robustRsUsed,\n                                                                  &robustRepairAttempted, &robustRepairSuccess);\n                                    if (robustRsUsed)\n                                        ++metrics->sparseRsFallbacks;\n                                    if (robustRepairAttempted && trackBit) {\n                                        metrics->erasureRepairAttemptMask |= trackBit;\n                                        if